# Fluent Bit DaemonSet Manifest
# This will be applied after Terraform creates the IAM role
# Fluent Bit runs on each node and collects logs from all pods

apiVersion: v1
kind: Namespace
metadata:
  name: amazon-cloudwatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: <FLUENT_BIT_ROLE_ARN>  # Replace with Terraform output
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: amazon-cloudwatch
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval   5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                modify
        Match               kube.*
        Rename              stream stdout
        Rename              stream stderr

    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.*
        region              <AWS_REGION>
        log_group_name      /aws/eks/<PROJECT_NAME>/cluster
        log_stream_prefix    fluent-bit-
        auto_create_group   true

    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.*auth-service*
        region              <AWS_REGION>
        log_group_name      /aws/eks/<PROJECT_NAME>/auth-service
        log_stream_prefix    fluent-bit-
        auto_create_group   true

    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.*expense-service*
        region              <AWS_REGION>
        log_group_name      /aws/eks/<PROJECT_NAME>/expense-service
        log_stream_prefix    fluent-bit-
        auto_create_group   true

    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.*receipt-service*
        region              <AWS_REGION>
        log_group_name      /aws/eks/<PROJECT_NAME>/receipt-service
        log_stream_prefix    fluent-bit-
        auto_create_group   true

    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.*notification-service*
        region              <AWS_REGION>
        log_group_name      /aws/eks/<PROJECT_NAME>/notification-service
        log_stream_prefix    fluent-bit-
        auto_create_group   true

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: runlogjournal
          mountPath: /run/log/journal
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: runlogjournal
        hostPath:
          path: /run/log/journal

